"""Generate docs/osdu-mapping.md from the mapping tuples.

The mapping is defined once, in ``hugin.osdu.mapping``, and this renders it.
A schema mapping maintained in a markdown table and in code separately
disagrees with itself within a month, and the table is always the half that
is wrong, because it is the half nothing executes.

    python scripts/osdu_report.py                 # write docs/osdu-mapping.md
    python scripts/osdu_report.py --check         # fail if the file is stale
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from hugin.osdu import mapping  # noqa: E402

OUTPUT = REPO_ROOT / "docs" / "osdu-mapping.md"


def escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def table(columns) -> str:
    lines = [
        "| Gold column | OSDU path | Transform | Note |",
        "|---|---|---|---|",
    ]
    for entry in columns:
        gold = f"`{entry.gold_column}`" if entry.gold_column else "*(none)*"
        osdu = f"`{entry.osdu_path}`" if entry.osdu_path else "*(not emitted)*"
        lines.append(
            f"| {escape(gold)} | {escape(osdu)} "
            f"| {escape(entry.transform)} | {escape(entry.note)} |"
        )
    return "\n".join(lines)


def render() -> str:
    today = dt.date.today().isoformat()
    return f"""# Gold to OSDU, column by column

Generated by `scripts/osdu_report.py` from `src/hugin/osdu/mapping.py` on
{today}. Do not edit this file; edit the mapping and regenerate. The point of
generating it is that the document and the code cannot drift apart, which is
what happens to every schema mapping maintained as prose.

SPEC.md section 7 cuts a real OSDU deployment: mapping plus validator is the
deliverable. ADR 008 argues that line. What follows is therefore a *mapping*
that runs and is schema-checked, not an integration.

## The three kinds

| Gold table | OSDU kind | Grain change |
|---|---|---|
| `gold.dim_wellbore` | `{mapping.WELLBORE_KIND}` | none - a version is a version |
| `gold.fct_log_sample` | `{mapping.WELL_LOG_KIND}` | **aggregates** - one per run |
| `gold.fct_trajectory` | `{mapping.TRAJECTORY_KIND}` | **aggregates** - one per survey |

The two aggregations are the substance of this mapping. OSDU's
work-product-components describe a logging run and a survey; the readings and
the stations live in bulk datasets those records point at. A mapping that
emitted one OSDU record per fact row would be a mapping written without reading
the schema.

## `dim_wellbore` -> master-data--Wellbore

{table(mapping.WELLBORE_COLUMNS)}

## `fct_log_sample` -> work-product-component--WellLog

{table(mapping.WELL_LOG_COLUMNS)}

## `fct_trajectory` -> work-product-component--WellboreTrajectory

{table(mapping.TRAJECTORY_COLUMNS)}

## Gold columns with no OSDU home

The interesting half. A column here is not omitted by oversight; it has
nowhere to go, and the reason is the point.

| Column | What it is | Why it does not map |
|---|---|---|
"""


def render_unmapped() -> str:
    lines = []
    for column, what, why in mapping.UNMAPPED_GOLD_COLUMNS:
        lines.append(f"| `{column}` | {escape(what)} | {escape(why)} |")
    return "\n".join(lines)


def render_unfilled() -> str:
    lines = [
        "",
        "## OSDU properties this mapping leaves empty",
        "",
        "Read this list before believing any claim about OSDU readiness. Each",
        "of these is a property the schema defines, that a real platform would",
        "want, and that nothing in this repository can honestly fill.",
        "",
        "| OSDU property | What it would take |",
        "|---|---|",
    ]
    for prop, need in mapping.UNFILLED_OSDU_PROPERTIES:
        lines.append(f"| `{prop}` | {escape(need)} |")
    lines += [
        "",
        "## Validation",
        "",
        "```",
        "python -m hugin.osdu.validate_osdu --write data/osdu   # map gold, validate, write",
        "python -m hugin.osdu.validate_osdu --records data/osdu # validate from disk, no Trino",
        "```",
        "",
        "The schemas in `src/hugin/osdu/schemas/` are **reduced local copies** of",
        "the published OSDU 1.0.0 well-known schemas - that directory's README",
        "says exactly what was kept and what was dropped. A pass means the",
        "envelope, the kind, the id form and every mapped property are right. It",
        "does not mean an OSDU instance would accept the record: the table above",
        "lists what is still missing.",
        "",
        "`tests/test_osdu.py` runs the whole mapping over fixture rows and",
        "validates the output, so the mapping is covered in CI without a",
        "warehouse and without a platform.",
        "",
    ]
    return "\n".join(lines)


def full_document() -> str:
    return render() + render_unmapped() + "\n" + render_unfilled()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = parser.parse_args()

    document = full_document()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        # The generation date changes daily and is not drift.
        if _without_date(current) != _without_date(document):
            print(f"{OUTPUT} is stale. Run: python scripts/osdu_report.py")
            return 1
        print(f"{OUTPUT} is up to date")
        return 0

    OUTPUT.write_text(document, encoding="utf-8")
    print(f"written: {OUTPUT} ({len(document.splitlines())} lines)")
    return 0


def _without_date(text: str) -> str:
    import re

    return re.sub(r"\d{4}-\d{2}-\d{2}", "<date>", text)


if __name__ == "__main__":
    sys.exit(main())
