"""Generate docs/slo.md from the objectives in hugin.slo, with a live reading.

Same reasoning as scripts/osdu_report.py: the objectives are defined once, in
code that Airflow executes, and the document is rendered from them. An SLO
document maintained by hand describes the SLOs somebody meant to have.

    python scripts/slo_report.py            # render, with a live measurement
    python scripts/slo_report.py --no-measure   # render without touching Trino
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from hugin import slo as slo_module  # noqa: E402

OUTPUT = REPO_ROOT / "docs" / "slo.md"


def cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def render(measurements: list | None, as_of: dt.date | None) -> str:
    measured = {m.slo.name: m for m in (measurements or [])}
    today = dt.date.today().isoformat()

    header = f"""# Service level objectives

Generated by `scripts/slo_report.py` from `src/hugin/slo.py` on {today}. Do not
edit this file; edit the objectives and regenerate. The objectives are the ones
Airflow enforces - `hugin_daily.slo_check` calls the same `evaluate()` this
page renders - so the document cannot describe a policy the pipeline does not
have.

## What an objective is here

Three things, all required: a **number** the table must satisfy, the **SQL**
that measures it, and a sentence saying **what breaks** when it does not. A
threshold with no measurement is a wish. A measurement with no stated
consequence is a dashboard.

Three dimensions, failing differently:

* **Freshness** - how far the table's newest business date lags the replay
  clock (BR-01), in *replay* days. A table current as of replay day 400 is
  fresh even though the date on it is 2009. A negative value means the table is
  ahead of the clock, which a completed backfill makes normal.
* **Completeness** - row floors and non-null rates. A table that lost 90% of
  its rows still answers every query and still passes every `not_null` test on
  the rows that remain. dbt asks whether each row is legal; this asks whether
  enough of them are here.
* **Coverage** - BR-12 identity resolution, from `mart_identity_coverage`.
  The one metric that may legitimately fall when a new delivery arrives with
  names nothing recognises, which is why it is an objective and not a test.

## Where the thresholds come from

Floors sit **below** the measured value with headroom, so an objective does not
fail on legitimate variation. Every `Basis` column below names the measurement
it came from, so the next person to tighten one can see what they are
tightening against.

Three objectives are **deliberately not met** and are marked *known*. They
encode what a table is supposed to contain rather than what it currently does.
They are reported on every run and do not fail the DAG - an objective written
down as unmet is not an incident, and treating it as one teaches everyone to
ignore a red DAG, which is how the real breach gets missed.

## Enforcement

`hugin_daily` runs `slo_check` after `dbt_test`:

    ingest_bronze -> dbt_run_silver_gold -> dbt_test -> slo_check -> soda_scan

A blocking breach raises, the task turns red, and the run fails. Outside the
DAG:

    python -m hugin.slo                          # exit 1 on a blocking breach
    python -m hugin.slo --include-known-breaches # exit 1 on any breach
    python -m hugin.slo --json docs/slo-check.json
"""

    if as_of:
        met = sum(1 for m in measured.values() if m.ok)
        known = sum(1 for m in measured.values() if not m.ok and m.slo.known_breach)
        blocking = sum(1 for m in measured.values() if m.blocking)
        header += f"""
## Last measurement

Taken {today}, at replay date **{as_of.isoformat()}**: **{met} met, {known} known
breaches, {blocking} blocking.** Raw numbers in `docs/slo-check.json`.
"""

    sections = []
    for dimension, title in (
        ("freshness", "Freshness"),
        ("completeness", "Completeness"),
        ("coverage", "Coverage - BR-12"),
    ):
        rows = [s for s in slo_module.SLOS if s.dimension == dimension]
        if not rows:
            continue
        lines = [
            f"\n## {title}\n",
            "| Objective | Table | Target | Last reading | Consequence of breach | Basis |",
            "|---|---|---|---|---|---|",
        ]
        for s in rows:
            m = measured.get(s.name)
            if m is None:
                reading = "not measured"
            elif m.error:
                reading = "**error**"
            else:
                mark = "ok" if m.ok else ("known" if s.known_breach else "**BREACH**")
                reading = f"{m.value:,.4g} ({mark})"
            lines.append(
                f"| `{s.name.split('.')[-1]}` | `{s.table}` | {s.comparison} {s.threshold:,.4g} "
                f"{cell(s.unit)} | {reading} | {cell(s.consequence)} | {cell(s.basis)} |"
            )
        sections.append("\n".join(lines))

    breaches = [s for s in slo_module.SLOS if s.known_breach]
    known_section = ["\n## Known breaches, with diagnosis\n"]
    if not breaches:
        known_section.append("None.\n")
    else:
        known_section.append(
            "Each of these is an objective the pipeline does not meet today. They are "
            "listed here rather than lowered to fit, because an objective adjusted to "
            "match a broken number stops being an objective.\n"
        )
        for s in breaches:
            known_section += [
                f"\n### `{s.name}`\n",
                f"**Target**: {s.comparison} {s.threshold:,.4g} {s.unit}. "
                f"**Consequence if it stays this way**: {s.consequence}\n",
                f"{s.known_breach}\n",
            ]

    tail = """
## What has no SLO, and why

- **`gold.fct_drilling_state`.** Built from `silver.drilling_telemetry`, which
  Spark owns and which holds calibrated fixture data rather than Volve
  telemetry. A freshness objective over fixture timestamps would measure the
  fixture generator. It gets one on the day real WITSML telemetry streams
  through, and not before.
- **`mart_*` row counts.** They are derived from the gold tables that do have
  objectives. A mart floor would fail second and add nothing to the diagnosis.
- **Query latency.** That is `docs/performance.md` and SPEC.md section 13.
  Mixing a latency target into a data-quality objective makes both harder to
  read and makes it unclear which one paged you.
"""
    return header + "\n".join(sections) + "\n" + "\n".join(known_section) + tail


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--no-measure", action="store_true", help="render without querying Trino")
    args = parser.parse_args()

    measurements, as_of = None, None
    if not args.no_measure:
        as_of = slo_module.current_replay_date()
        measurements = slo_module.evaluate(replay_date=as_of)

    OUTPUT.write_text(render(measurements, as_of), encoding="utf-8")
    print(f"written: {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
